reticulate::use_virtualenv("/Users/lee/tensorflow-metal", required=TRUE)

source("~/GitHub/sheetCrunch/gpuMachineLearning.r", chdir=T)
library(ISLR)
data = Default[1:2000,]
variable="income"
predictors=NULL
min.n=5
split=0.15
split_by_group=NULL
the_group=NULL
type="xgbTreeNeuralNet"
tree_method="hist"
single_precision_histogram=FALSE
treedepth="2-20"
treedrop="0.01-0.99"
skipdrop="0.01-0.99"
xgbalpha="0-10"
xgbeta="0.01-0.99"
xgbgamma="0-300"
xgblambda="0-300"
xgbcolsample="0.01-0.99"
xgbsubsample="0.01-0.99"
xgbminchild="1-300"
maxdeltastep = "0-10"
scaleposweight = "0-10"
nrounds=500
test_nrounds=100
try=10
trees=500
svmc="1-5"
svmdegree="1-5"
svmscale="1-5"
svmsigma="1-5"
svmlength="1-5"
svmgammavector=NULL
neuralhiddenunits="1-10"
bartk="1-2"
bartbeta="1-2"
bartnu="1-2"
missing=missing
metric="Accuracy"
eval_metric="auc"
train="cv"
cvrepeats=5
number=20
Bayes=FALSE
folds=15
init_points=30
n_iter=5
save.directory=NULL
save.name=NULL
parallelMethod=NULL
PositiveClass= NULL
NegativeClass = NULL
save_plots=FALSE
scale=FALSE
seed=NULL
additional_validation_frame=NULL
nthread=-1
verbose=1
bayes_metric="test_accuracy"
parallelMethod="linux"
parallel_method="linux"
epochs=100
activation="adam"
dropout="0.8"
optimizer="sigmoid"
learning.rate=0.00001
loss="mse"
metric=c("mse", "mae")
start_kernel=15
pool_size=5
batch_size=256
model.type="First_CNN"
importance=FALSE
init_points=40
n_iter=10
n_gpus=1
eager=FALSE
previous.model=NULL
epochs_test=10
optimizer_vector=c("rmsprop", "sgd", "adam", "nadam", "adadelta", "adamax")
loss_vector=c("binary_crossentropy", "poisson", "hinge", "kl_divergence")
activation_vector=c("relu", "elu", "sigmoid", "tanh", "selu")
cv_seed=4





data=data[, c("Sample", "Group", "eccentricity", "perihelion", "obliquity", "co2_trend", "global_insolation", "insolation", "Benthic_d18O_Detrend")]
variable="Benthic_d18O_Detrend"
split_by_group="Group"
the_group="Parameter_Val"
type="xgbTreeNeuralNet"
model.split=0
epochs=10000
metric=c("mse", "mae")
start_kernel=5
pool_size=3
batch_size=64
model.type="First_CNN"
n_gpus=1
epochs_test=50
activation_vector=c("relu", "elu", "sigmoid", "tanh", "selu")
dropout=0.8
optimizer_vector=c("rmsprop", "sgd", "adam", "nadam", "adadelta", "adamax")
learning.rate=0.01
loss_vector=c("mse", "mae")
xgbalpha="0-10"
treedepth="2-30"
xgbgamma="0-100"
xgblambda="0-90"
xgbeta="0.01-0.99"
xgbsubsample="0.01-0.99"
xgbcolsample="0.01-0.99"
xgbminchild="1-100"
maxdeltastep="0-10"
scaleposweight="0-10"
xgb_metric="MAE"
nrounds=10000
test_nrounds=500
train="cv"
number=20
Bayes=FALSE
folds=10
init_points=80
n_iter=20
scale=FALSE
importance=FALSE
parallelMethod="linux"
tree_method="hist"
single_precision_histogram=FALSE
bayes_metric="test_mae"
early_stopping_rounds=NULL
save.directory="~/"
save.name="xgbnntest"
additional_validation_frame=test_data
xgb_eval_metric="rmse"
predictor="cpu_predictor"
